name: 'GitHub Push'
description: 'The desired files can be Repository Commit to Push.'
inputs:
  repository-name:
    description: 'Repository name'
    required: true
outputs:
  test:
    description: 'test'
runs:
  using: 'docker'
  image: 'Dockerfile'
