on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Hello world action step
      id: hello
      uses: selenehyun/gh-push@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COMMIT_FILES: ./Dockerfile
        REPO_FULLNAME: selenehyun/test
        BRANCH: master
    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
