on: [push]

jobs:
  dog_fooding:
    runs-on: ubuntu-latest
    name: Dog Fooding
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: My food
      uses: selenehyun/gh-push@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COMMIT_FILES: ./Dockerfile
        REPO_FULLNAME: selenehyun/test
        BRANCH: master
